package com.simnect.mengua.entities;

// Generated Mar 13, 2014 9:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "game", catalog = "menguadb")
public class Game implements java.io.Serializable {

	private static final long serialVersionUID = 4585667108076690850L;
	private Long gameId;
	private String desc;
	private Date createdAt;
	private Date updatedAt;
	private Set<UserGame> userGames = new HashSet<UserGame>(0);

	public Game() {
	}

	public Game(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Game(String desc, Date createdAt, Date updatedAt,
			Set<UserGame> userGames) {
		this.desc = desc;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.userGames = userGames;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "game_id", unique = true, nullable = false)
	public Long getGameId() {
		return this.gameId;
	}

	public void setGameId(Long gameId) {
		this.gameId = gameId;
	}

	@Column(name = "desc", length = 16777215)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "game")
	public Set<UserGame> getUserGames() {
		return this.userGames;
	}

	public void setUserGames(Set<UserGame> userGames) {
		this.userGames = userGames;
	}

}
