package com.simnect.mengua.entities;

// Generated Mar 13, 2014 9:52:52 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.simnect.mengua.entities.base.MenguaEntity;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "game")
public class Game extends MenguaEntity implements Serializable {

	private static final long serialVersionUID = 4585667108076690850L;
	private Long gameId;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private Set<UserGame> userGames = new HashSet<UserGame>(0);

	public Game() {
	}

	public Game(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Game(String description, Date createdAt, Date updatedAt,
			Set<UserGame> userGames) {
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.userGames = userGames;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "game_id", unique = true, nullable = false)
	public Long getGameId() {
		return this.gameId;
	}

	public void setGameId(Long gameId) {
		this.gameId = gameId;
	}

	@Column(name = "description", length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "game")
	public Set<UserGame> getUserGames() {
		return this.userGames;
	}

	public void setUserGames(Set<UserGame> userGames) {
		this.userGames = userGames;
	}

	@Override
	public Long retrievePKId() {
		return this.gameId;
	}

	@Override
	public void syncCreatedAt() {
		this.createdAt = new Date();
	}

	@Override
	public void syncUpdatedAt() {
		this.updatedAt = new Date();
	}
	
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
