package com.simnect.mengua.entities;

// Generated Mar 13, 2014 9:52:52 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.simnect.mengua.entities.base.MenguaEntity;

/**
 * Like generated by hbm2java
 */
@Entity
@Table(name = "like")
public class Like extends MenguaEntity implements Serializable {

  private static final long serialVersionUID = 1034494740196658234L;
  private Long likeId;
  private User user;
  private long targetId;
  private String likeType;
  private Date createdAt;
  private Date updatedAt;

  public Like() {
  }

  public Like(User user, long targetId, String likeType, Date createdAt,
      Date updatedAt) {
    this.user = user;
    this.targetId = targetId;
    this.likeType = likeType;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "like_id", unique = true, nullable = false)
  public Long getLikeId() {
    return this.likeId;
  }

  public void setLikeId(Long likeId) {
    this.likeId = likeId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  @Column(name = "target_id", nullable = false)
  public long getTargetId() {
    return this.targetId;
  }

  public void setTargetId(long targetId) {
    this.targetId = targetId;
  }

  @Column(name = "like_type", nullable = false, length = 128)
  public String getLikeType() {
    return this.likeType;
  }

  public void setLikeType(String likeType) {
    this.likeType = likeType;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created_at", nullable = false, length = 19)
  public Date getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updated_at", nullable = false, length = 19)
  public Date getUpdatedAt() {
    return this.updatedAt;
  }

  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Override
  public Long retrievePKId() {
    return likeId;
  }

  @Override
  public void syncCreatedAt() {
    this.createdAt = new Date();
  }

  @Override
  public void syncUpdatedAt() {
    this.updatedAt = new Date();
  }

  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this);
  }
}
