package com.simnect.mengua.entities;

// Generated Mar 13, 2014 9:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "menguadb")
public class Media implements java.io.Serializable {

	private static final long serialVersionUID = 2175951199399116445L;
	private Long mediaId;
	private Snippet snippet;
	private String mediaUrl;
	private Date createdAt;
	private Date updatedAt;

	public Media() {
	}

	public Media(Snippet snippet, Date createdAt, Date updatedAt) {
		this.snippet = snippet;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Media(Snippet snippet, String mediaUrl, Date createdAt,
			Date updatedAt) {
		this.snippet = snippet;
		this.mediaUrl = mediaUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "media_id", unique = true, nullable = false)
	public Long getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(Long mediaId) {
		this.mediaId = mediaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "snippet_id", nullable = false)
	public Snippet getSnippet() {
		return this.snippet;
	}

	public void setSnippet(Snippet snippet) {
		this.snippet = snippet;
	}

	@Column(name = "media_url", length = 2083)
	public String getMediaUrl() {
		return this.mediaUrl;
	}

	public void setMediaUrl(String mediaUrl) {
		this.mediaUrl = mediaUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
