package com.simnect.mengua.entities;

// Generated Mar 13, 2014 9:52:52 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.ToStringBuilder;

import com.simnect.mengua.entities.base.MenguaEntity;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "token")
public class Token extends MenguaEntity implements Serializable {

	private static final long serialVersionUID = -1177887850175817038L;
	private Long tokenId;
	private User user;
	private String context;
	private Date createdAt;
	private Date updatedAt;

	public Token() {
	}

	public Token(User user, Date createdAt, Date updatedAt) {
		this.user = user;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Token(User user, String context, Date createdAt, Date updatedAt) {
		this.user = user;
		this.context = context;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "token_id", unique = true, nullable = false)
	public Long getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Long tokenId) {
		this.tokenId = tokenId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "context", length = 16777215)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	
	@Override
	public Long retrievePKId() {
		return this.tokenId;
	}

	@Override
	public void syncCreatedAt() {
		this.createdAt = new Date();
	}

	@Override
	public void syncUpdatedAt() {
		this.updatedAt = new Date();
	}
	
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this);
  }
}
